/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.FormationDAO;
import dao.ResultatDAO;
import dao.StagiaireDAO;
import gestStudent.MainMethodes;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.Formation;
import model.Stagiaire;

/**
 *
 * @author afpa
 */
public class Fenetre extends javax.swing.JFrame {

    String nomStag;
    String prenomStag;
    Formation formationStagiaire;
    FormationTable formationTable = new FormationTable(FormationDAO.findAll());
    StagiaireTable stagiaireTable = new StagiaireTable(StagiaireDAO.findAll());
    ResultatTable resultatTable = new ResultatTable(new ArrayList());

    /**
     * Creates new form NewJFrame
     */
    public Fenetre() {
        initComponents();
        //Reccupération de la liste formation et affichage dans la ComboBox
        List<Formation> formations = FormationDAO.findAll();
        for (Formation form : formations) {
            FormationListAddCbbox.addItem(form);
        }

        //Ajout d'un ecouteur pour détecter le clic sur le tableau de stagiaire
        stagListTbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    tblStagValueChanged(evt);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameTabPane = new javax.swing.JTabbedPane();
        JFrameStagPnl = new javax.swing.JPanel();
        stagListPnl = new javax.swing.JPanel();
        stagListLbl = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        stagListTbl = new javax.swing.JTable();
        stagInfosPnl = new javax.swing.JPanel();
        stagAddEditTabPane = new javax.swing.JTabbedPane();
        stagAddFieldPnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NomStagLbl = new javax.swing.JLabel();
        NomStagAddFieldTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        PrenomStagLbl = new javax.swing.JLabel();
        PrenomStagAddFieldTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        FormationListAddLbl = new javax.swing.JLabel();
        FormationListAddCbbox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        JDlgValidAddBtn = new javax.swing.JButton();
        stagEditFieldPnl = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        NomStagEditLbl = new javax.swing.JLabel();
        NomStagEditFieldTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        PrenomStagLbl1 = new javax.swing.JLabel();
        PrenomStagEditFieldTxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        FormationListEditLbl = new javax.swing.JLabel();
        FormationListEditCbbox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        JDlgValidEditBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        stagNotesPnl = new javax.swing.JPanel();
        stagNomResultsLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stagResultsTbl = new javax.swing.JTable();
        JFrameFormPnl = new javax.swing.JPanel();
        formMenuPnl = new javax.swing.JPanel();
        formationListLbl = new javax.swing.JLabel();
        formContentPnl = new javax.swing.JPanel();
        formationListScrPane = new javax.swing.JScrollPane();
        FormationListTbl = new javax.swing.JTable();
        addFormButton = new javax.swing.JButton();
        JFrameMenu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuEdit = new javax.swing.JMenu();
        MenuFAQ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestStudent");
        setMinimumSize(new java.awt.Dimension(500, 500));

        JFrameTabPane.setPreferredSize(new java.awt.Dimension(1000, 720));

        JFrameStagPnl.setPreferredSize(new java.awt.Dimension(1000, 700));
        JFrameStagPnl.setLayout(new javax.swing.BoxLayout(JFrameStagPnl, javax.swing.BoxLayout.Y_AXIS));

        stagListPnl.setFocusTraversalPolicyProvider(true);
        stagListPnl.setMaximumSize(new java.awt.Dimension(33075, 375));
        stagListPnl.setPreferredSize(new java.awt.Dimension(1000, 30));
        stagListPnl.setLayout(new javax.swing.BoxLayout(stagListPnl, javax.swing.BoxLayout.Y_AXIS));

        stagListLbl.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        stagListLbl.setText("Liste des stagiaires");
        stagListPnl.add(stagListLbl);

        JScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 500));

        stagListTbl.setModel(stagiaireTable);
        JScrollPane1.setViewportView(stagListTbl);

        stagListPnl.add(JScrollPane1);

        JFrameStagPnl.add(stagListPnl);

        stagInfosPnl.setMaximumSize(new java.awt.Dimension(32767, 300));
        stagInfosPnl.setPreferredSize(new java.awt.Dimension(1082, 300));
        stagInfosPnl.setLayout(new javax.swing.BoxLayout(stagInfosPnl, javax.swing.BoxLayout.LINE_AXIS));

        stagAddEditTabPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        stagAddFieldPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajouter", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        stagAddFieldPnl.setForeground(new java.awt.Color(219, 49, 49));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        NomStagLbl.setText("Veuillez entrer le nom du stagiaire");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NomStagLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NomStagLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PrenomStagLbl.setText("Veuillez entrer le prénom du stagiaire");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PrenomStagLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PrenomStagLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FormationListAddLbl.setText("Veuillez sélectionner une formation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FormationListAddLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FormationListAddLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FormationListAddCbbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormationListAddCbboxActionPerformed(evt);
            }
        });

        JDlgValidAddBtn.setText("Valider");
        JDlgValidAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDlgValidAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JDlgValidAddBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JDlgValidAddBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout stagAddFieldPnlLayout = new javax.swing.GroupLayout(stagAddFieldPnl);
        stagAddFieldPnl.setLayout(stagAddFieldPnlLayout);
        stagAddFieldPnlLayout.setHorizontalGroup(
            stagAddFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(stagAddFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stagAddFieldPnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(stagAddFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomStagAddFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PrenomStagAddFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FormationListAddCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        stagAddFieldPnlLayout.setVerticalGroup(
            stagAddFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(stagAddFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stagAddFieldPnlLayout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(NomStagAddFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PrenomStagAddFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(FormationListAddCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );

        stagAddEditTabPane.addTab("Ajouter", stagAddFieldPnl);

        stagEditFieldPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        NomStagEditLbl.setText("Modifier le nom du stagiaire");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NomStagEditLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NomStagEditLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PrenomStagLbl1.setText("Modifier le prénom du stagiaire");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PrenomStagLbl1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PrenomStagLbl1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FormationListEditLbl.setText("Modifier la formation du stagiaire");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FormationListEditLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FormationListEditLbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JDlgValidEditBtn.setText("Valider");
        JDlgValidEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDlgValidEditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JDlgValidEditBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JDlgValidEditBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout stagEditFieldPnlLayout = new javax.swing.GroupLayout(stagEditFieldPnl);
        stagEditFieldPnl.setLayout(stagEditFieldPnlLayout);
        stagEditFieldPnlLayout.setHorizontalGroup(
            stagEditFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(stagEditFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stagEditFieldPnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(stagEditFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomStagEditFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PrenomStagEditFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FormationListEditCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        stagEditFieldPnlLayout.setVerticalGroup(
            stagEditFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(stagEditFieldPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stagEditFieldPnlLayout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(NomStagEditFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PrenomStagEditFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(FormationListEditCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );

        stagAddEditTabPane.addTab("Editer", stagEditFieldPnl);

        stagInfosPnl.add(stagAddEditTabPane);

        jPanel9.setMaximumSize(new java.awt.Dimension(15, 15));
        jPanel9.setMinimumSize(new java.awt.Dimension(30, 30));
        jPanel9.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        stagInfosPnl.add(jPanel9);

        stagNotesPnl.setLayout(new javax.swing.BoxLayout(stagNotesPnl, javax.swing.BoxLayout.Y_AXIS));

        stagNomResultsLbl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        stagNomResultsLbl.setText("Notes de :");
        stagNotesPnl.add(stagNomResultsLbl);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 345));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 266));

        stagResultsTbl.setModel(resultatTable);
        jScrollPane1.setViewportView(stagResultsTbl);

        stagNotesPnl.add(jScrollPane1);

        stagInfosPnl.add(stagNotesPnl);

        JFrameStagPnl.add(stagInfosPnl);

        JFrameTabPane.addTab("Stagiaires", JFrameStagPnl);

        JFrameFormPnl.setPreferredSize(new java.awt.Dimension(1000, 700));
        JFrameFormPnl.setLayout(new javax.swing.BoxLayout(JFrameFormPnl, javax.swing.BoxLayout.Y_AXIS));

        formMenuPnl.setMinimumSize(new java.awt.Dimension(1000, 30));

        formationListLbl.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        formationListLbl.setText("Liste des formations");

        javax.swing.GroupLayout formMenuPnlLayout = new javax.swing.GroupLayout(formMenuPnl);
        formMenuPnl.setLayout(formMenuPnlLayout);
        formMenuPnlLayout.setHorizontalGroup(
            formMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formMenuPnlLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(formationListLbl)
                .addContainerGap(535, Short.MAX_VALUE))
        );
        formMenuPnlLayout.setVerticalGroup(
            formMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formMenuPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(formationListLbl))
        );

        JFrameFormPnl.add(formMenuPnl);

        formContentPnl.setPreferredSize(new java.awt.Dimension(1000, 700));

        FormationListTbl.setModel(formationTable);
        formationListScrPane.setViewportView(FormationListTbl);

        addFormButton.setText("Ajouter une Formation");
        addFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formContentPnlLayout = new javax.swing.GroupLayout(formContentPnl);
        formContentPnl.setLayout(formContentPnlLayout);
        formContentPnlLayout.setHorizontalGroup(
            formContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formationListScrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
            .addGroup(formContentPnlLayout.createSequentialGroup()
                .addComponent(addFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formContentPnlLayout.setVerticalGroup(
            formContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContentPnlLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(formationListScrPane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        JFrameFormPnl.add(formContentPnl);

        JFrameTabPane.addTab("Formations", JFrameFormPnl);

        getContentPane().add(JFrameTabPane, java.awt.BorderLayout.NORTH);

        MenuFile.setText("File");
        JFrameMenu.add(MenuFile);

        MenuEdit.setText("Edit");
        JFrameMenu.add(MenuEdit);

        MenuFAQ.setText("?");
        JFrameMenu.add(MenuFAQ);

        setJMenuBar(JFrameMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFormButtonActionPerformed

    }//GEN-LAST:event_addFormButtonActionPerformed
    //Permet la réccupération de la ligne selectionnée dans le tableau et donc du stagiaire correspondant à celle-ci
    private void tblStagValueChanged(ListSelectionEvent evt) {

        int tableRow = stagListTbl.getSelectedRow();                                                            //reccupère la ligne selectonnée dans le tableau
        Stagiaire stag = stagiaireTable.getStagiaire(tableRow);                                              //Retrouyve le stagiaire de la ligne selectionnée
        resultatTable.setResultatList(ResultatDAO.findBy(stag));                                            //Affiche le tableau des notes
        //MAJ du nom du stagiaire
        stagNomResultsLbl.setText("Notes de : " + stag.getNom() + " " + stag.getPrenom());      
        NomStagEditFieldTxt.setText(stag.getNom());                                         
        PrenomStagEditFieldTxt.setText(stag.getPrenom());
        
        Formation stagFormation = stag.getForm();                                                              //Reccupère la formation du stagiaire
        List<Formation> formations = FormationDAO.findAll();                                             //Affiche la liste de formations

        FormationListEditCbbox.removeAllItems();                                                                //Clear la ComboBox
        FormationListEditCbbox.addItem(stagFormation);
        for (Formation form : formations) {
            if (!form.equals(stagFormation)) {
                FormationListEditCbbox.addItem(form);
            }
        }
        resultatTable.fireTableDataChanged();

    }

    private void JDlgValidAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDlgValidAddBtnActionPerformed
        prenomStag = PrenomStagAddFieldTxt.getText();
        nomStag = NomStagAddFieldTxt.getText();
        formationStagiaire = (Formation) FormationListAddCbbox.getSelectedItem();
        //Formation formation = new Formation (formationStagiaire);
        Stagiaire stagiaire = new Stagiaire(MainMethodes.matricule(), nomStag, prenomStag, formationStagiaire);

        try {
            StagiaireDAO.insert(stagiaire);
            NomStagAddFieldTxt.setText(null);
            PrenomStagAddFieldTxt.setText(null);
        } catch (Exception ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JDlgValidAddBtnActionPerformed

    private void JDlgValidEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDlgValidEditBtnActionPerformed
        prenomStag = PrenomStagEditFieldTxt.getText();
        nomStag = NomStagEditFieldTxt.getText();
        int tableRow = stagListTbl.getSelectedRow();
        Stagiaire stag = stagiaireTable.getStagiaire(tableRow);
        formationStagiaire = (Formation) FormationListEditCbbox.getSelectedItem();

        Stagiaire stagiaire = new Stagiaire(stag.getId(), nomStag, prenomStag, formationStagiaire);

        try {
            StagiaireDAO.update(stagiaire);
            NomStagEditFieldTxt.setText(null);
            PrenomStagEditFieldTxt.setText(null);
            FormationListEditCbbox.removeAllItems();
            resultatTable.fireTableDataChanged();
        } catch (Exception ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_JDlgValidEditBtnActionPerformed

    private void FormationListAddCbboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormationListAddCbboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormationListAddCbboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    public FormationTable getFormationTable() {
        return formationTable;
    }

    public StagiaireTable getStagiaireTable() {
        return stagiaireTable;
    }

    public ResultatTable getResultatTable() {
        return resultatTable;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Formation> FormationListAddCbbox;
    private javax.swing.JLabel FormationListAddLbl;
    private javax.swing.JComboBox<Formation> FormationListEditCbbox;
    private javax.swing.JLabel FormationListEditLbl;
    public javax.swing.JTable FormationListTbl;
    private javax.swing.JButton JDlgValidAddBtn;
    private javax.swing.JButton JDlgValidEditBtn;
    public javax.swing.JPanel JFrameFormPnl;
    private javax.swing.JMenuBar JFrameMenu;
    public javax.swing.JPanel JFrameStagPnl;
    private javax.swing.JTabbedPane JFrameTabPane;
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFAQ;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JTextField NomStagAddFieldTxt;
    private javax.swing.JTextField NomStagEditFieldTxt;
    private javax.swing.JLabel NomStagEditLbl;
    private javax.swing.JLabel NomStagLbl;
    private javax.swing.JTextField PrenomStagAddFieldTxt;
    private javax.swing.JTextField PrenomStagEditFieldTxt;
    private javax.swing.JLabel PrenomStagLbl;
    private javax.swing.JLabel PrenomStagLbl1;
    private javax.swing.JButton addFormButton;
    public javax.swing.JPanel formContentPnl;
    private javax.swing.JPanel formMenuPnl;
    private javax.swing.JLabel formationListLbl;
    private javax.swing.JScrollPane formationListScrPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane stagAddEditTabPane;
    private javax.swing.JPanel stagAddFieldPnl;
    private javax.swing.JPanel stagEditFieldPnl;
    private javax.swing.JPanel stagInfosPnl;
    private javax.swing.JLabel stagListLbl;
    private javax.swing.JPanel stagListPnl;
    private javax.swing.JTable stagListTbl;
    private javax.swing.JLabel stagNomResultsLbl;
    public javax.swing.JPanel stagNotesPnl;
    public javax.swing.JTable stagResultsTbl;
    // End of variables declaration//GEN-END:variables
}
