/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.OwnerDAO;
import dao.ShipClassDAO;
import dao.ShipDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Owner;
import model.Ship;
import model.ShipClass;

/**
 *
 * @author afpa
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        List<Owner> owners = OwnerDAO.findAll();
        for (Owner own : owners){
            shipOwnerCbBox.addItem(own);
        }
        List<ShipClass> shipClasses = ShipClassDAO.findAll();
        for (ShipClass sc : shipClasses){
        shipClassCbBox.addItem(sc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        shipNameTxtFldLbl = new javax.swing.JLabel();
        shipNameTxtFld = new javax.swing.JTextField();
        sailNumbTxtFldLbl = new javax.swing.JLabel();
        sailNumbTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        shipOwnerCbBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        validNewShipBtn = new javax.swing.JButton();
        shipClassCbBox = new javax.swing.JComboBox<>();
        shipListPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        formPnl.setPreferredSize(new java.awt.Dimension(550, 626));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajout d'un nouveau navire", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        shipNameTxtFldLbl.setText("Veuillez entrer le nom du navire");
        shipNameTxtFldLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        shipNameTxtFld.setName(""); // NOI18N

        sailNumbTxtFldLbl.setText("Veuillez entrer le numéro de voile du voilier");
        sailNumbTxtFldLbl.setAlignmentX(5.0F);

        jLabel1.setText("Veuillez selectionner le propritaire du navire");

        shipOwnerCbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shipOwnerCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipOwnerCbBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Veuillez entrer la classe du navire");

        validNewShipBtn.setText("Valider");
        validNewShipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validNewShipBtnActionPerformed(evt);
            }
        });

        shipClassCbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shipOwnerCbBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(shipNameTxtFld)
                                .addComponent(sailNumbTxtFldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sailNumbTxtFld)
                                .addComponent(shipNameTxtFldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(validNewShipBtn))
                            .addComponent(shipClassCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(shipNameTxtFldLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sailNumbTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sailNumbTxtFldLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipOwnerCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipClassCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(validNewShipBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formPnlLayout = new javax.swing.GroupLayout(formPnl);
        formPnl.setLayout(formPnlLayout);
        formPnlLayout.setHorizontalGroup(
            formPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPnlLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        formPnlLayout.setVerticalGroup(
            formPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPnlLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(formPnl);

        javax.swing.GroupLayout shipListPnlLayout = new javax.swing.GroupLayout(shipListPnl);
        shipListPnl.setLayout(shipListPnlLayout);
        shipListPnlLayout.setHorizontalGroup(
            shipListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        shipListPnlLayout.setVerticalGroup(
            shipListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        getContentPane().add(shipListPnl);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validNewShipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validNewShipBtnActionPerformed
        String shipName = shipNameTxtFld.getText();
        int sailNum = Integer.parseInt(sailNumbTxtFld.getText());
        Owner owner = (Owner) shipOwnerCbBox.getSelectedItem();
        ShipClass sc = (ShipClass) shipClassCbBox.getSelectedItem();
        
        Ship ship = new Ship(sailNum, shipName, sc, owner);
        
        try {
            ShipDAO.insert(ship);
            shipNameTxtFld.setText(null);
            sailNumbTxtFld.setText(null);
        } catch (Exception ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_validNewShipBtnActionPerformed

    private void shipOwnerCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipOwnerCbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shipOwnerCbBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sailNumbTxtFld;
    private javax.swing.JLabel sailNumbTxtFldLbl;
    private javax.swing.JComboBox<String> shipClassCbBox;
    private javax.swing.JPanel shipListPnl;
    private javax.swing.JTextField shipNameTxtFld;
    private javax.swing.JLabel shipNameTxtFldLbl;
    private javax.swing.JComboBox<String> shipOwnerCbBox;
    private javax.swing.JButton validNewShipBtn;
    // End of variables declaration//GEN-END:variables
}
