/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.FormationDAO;
import java.awt.event.ItemEvent;
import java.util.List;
import model.Formation;

/**
 *
 * @author afpa
 */
public class Fenetre extends javax.swing.JFrame {

    
    
    AddFormationDlg formationDlg;
    FormationTable formationTable = new FormationTable(FormationDAO.findAll());

    /**
     * Creates new form NewJFrame
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameTabPane = new javax.swing.JTabbedPane();
        JFrameStagPnl = new javax.swing.JPanel();
        StagMenuPnl = new javax.swing.JPanel();
        showStagListButton = new javax.swing.JButton();
        addStagButton = new javax.swing.JButton();
        stagContentPnl = new javax.swing.JPanel();
        JFrameFormPnl = new javax.swing.JPanel();
        FormMenuPnl = new javax.swing.JPanel();
        showListformationTglBtn = new javax.swing.JToggleButton();
        addFormButton = new javax.swing.JButton();
        FormContentPnl = new javax.swing.JPanel();
        formationListScrPane = new javax.swing.JScrollPane();
        FormationListTbl = new javax.swing.JTable();
        JFrameMenu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuEdit = new javax.swing.JMenu();
        MenuFAQ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JFrameStagPnl.setLayout(new java.awt.BorderLayout());

        StagMenuPnl.setLayout(new java.awt.GridLayout(1, 0));

        showStagListButton.setText("Afficher la liste des stagiaires");
        StagMenuPnl.add(showStagListButton);

        addStagButton.setText("Ajouter un stagiaire");
        StagMenuPnl.add(addStagButton);

        JFrameStagPnl.add(StagMenuPnl, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout stagContentPnlLayout = new javax.swing.GroupLayout(stagContentPnl);
        stagContentPnl.setLayout(stagContentPnlLayout);
        stagContentPnlLayout.setHorizontalGroup(
            stagContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        stagContentPnlLayout.setVerticalGroup(
            stagContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        JFrameStagPnl.add(stagContentPnl, java.awt.BorderLayout.LINE_END);

        JFrameTabPane.addTab("Stagiaires", JFrameStagPnl);

        JFrameFormPnl.setLayout(new java.awt.BorderLayout());

        FormMenuPnl.setLayout(new java.awt.GridLayout(1, 0));

        showListformationTglBtn.setText("Afficher la liste des formations");
        showListformationTglBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showListformationTglBtnItemStateChanged(evt);
            }
        });
        showListformationTglBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListformationTglBtnActionPerformed(evt);
            }
        });
        FormMenuPnl.add(showListformationTglBtn);

        addFormButton.setText("Ajouter une Formation");
        addFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFormButtonActionPerformed(evt);
            }
        });
        FormMenuPnl.add(addFormButton);

        JFrameFormPnl.add(FormMenuPnl, java.awt.BorderLayout.NORTH);

        FormationListTbl.setModel(formationTable);
        formationListScrPane.setViewportView(FormationListTbl);

        javax.swing.GroupLayout FormContentPnlLayout = new javax.swing.GroupLayout(FormContentPnl);
        FormContentPnl.setLayout(FormContentPnlLayout);
        FormContentPnlLayout.setHorizontalGroup(
            FormContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formationListScrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        FormContentPnlLayout.setVerticalGroup(
            FormContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormContentPnlLayout.createSequentialGroup()
                .addComponent(formationListScrPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 169, Short.MAX_VALUE))
        );

        JFrameFormPnl.add(FormContentPnl, java.awt.BorderLayout.LINE_END);

        JFrameTabPane.addTab("Formations", JFrameFormPnl);

        getContentPane().add(JFrameTabPane, java.awt.BorderLayout.NORTH);

        MenuFile.setText("File");
        JFrameMenu.add(MenuFile);

        MenuEdit.setText("Edit");
        JFrameMenu.add(MenuEdit);

        MenuFAQ.setText("?");
        JFrameMenu.add(MenuFAQ);

        setJMenuBar(JFrameMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFormButtonActionPerformed
        formationDlg =new AddFormationDlg(this, true);
        formationDlg.setVisible(true);
    }//GEN-LAST:event_addFormButtonActionPerformed

    private void showListformationTglBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListformationTglBtnActionPerformed
     
    }//GEN-LAST:event_showListformationTglBtnActionPerformed

    private void showListformationTglBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showListformationTglBtnItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            FormContentPnl.setVisible(true);       
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            FormContentPnl.setVisible(false);           
        }
    }//GEN-LAST:event_showListformationTglBtnItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    public FormationTable getFormationTable() {
        return formationTable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel FormContentPnl;
    private javax.swing.JPanel FormMenuPnl;
    public javax.swing.JTable FormationListTbl;
    public javax.swing.JPanel JFrameFormPnl;
    private javax.swing.JMenuBar JFrameMenu;
    public javax.swing.JPanel JFrameStagPnl;
    private javax.swing.JTabbedPane JFrameTabPane;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFAQ;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JPanel StagMenuPnl;
    private javax.swing.JButton addFormButton;
    private javax.swing.JButton addStagButton;
    private javax.swing.JScrollPane formationListScrPane;
    private javax.swing.JToggleButton showListformationTglBtn;
    private javax.swing.JButton showStagListButton;
    private javax.swing.JPanel stagContentPnl;
    // End of variables declaration//GEN-END:variables
}
