/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.FormationDAO;
import dao.StagiaireDAO;
import java.awt.event.ItemEvent;

/**
 *
 * @author afpa
 */
public class Fenetre extends javax.swing.JFrame {


    
    FormationTable formationTable = new FormationTable(FormationDAO.findAll());
    StagiaireTable stagiaireTable = new StagiaireTable(StagiaireDAO.findAll());

    /**
     * Creates new form NewJFrame
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameTabPane = new javax.swing.JTabbedPane();
        JFrameStagPnl = new javax.swing.JPanel();
        StagMenuPnl = new javax.swing.JPanel();
        showStagiaireListTglBtn = new javax.swing.JToggleButton();
        addStagButton = new javax.swing.JButton();
        StagContentPnl = new javax.swing.JPanel();
        StagTblSPane = new javax.swing.JScrollPane();
        StagiaireListTbl = new javax.swing.JTable();
        JFrameFormPnl = new javax.swing.JPanel();
        FormMenuPnl = new javax.swing.JPanel();
        showListformationTglBtn = new javax.swing.JToggleButton();
        addFormButton = new javax.swing.JButton();
        FormContentPnl = new javax.swing.JPanel();
        formationListScrPane = new javax.swing.JScrollPane();
        FormationListTbl = new javax.swing.JTable();
        JFrameMenu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuEdit = new javax.swing.JMenu();
        MenuFAQ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestStudent");

        JFrameStagPnl.setLayout(new javax.swing.BoxLayout(JFrameStagPnl, javax.swing.BoxLayout.PAGE_AXIS));

        showStagiaireListTglBtn.setText("Afficher la liste des stagiaires");
        showStagiaireListTglBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showStagiaireListTglBtnItemStateChanged(evt);
            }
        });

        addStagButton.setText("Ajouter un stagiaire");
        addStagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StagMenuPnlLayout = new javax.swing.GroupLayout(StagMenuPnl);
        StagMenuPnl.setLayout(StagMenuPnlLayout);
        StagMenuPnlLayout.setHorizontalGroup(
            StagMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StagMenuPnlLayout.createSequentialGroup()
                .addComponent(showStagiaireListTglBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addStagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StagMenuPnlLayout.setVerticalGroup(
            StagMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showStagiaireListTglBtn)
            .addComponent(addStagButton)
        );

        JFrameStagPnl.add(StagMenuPnl);

        StagiaireListTbl.setModel(stagiaireTable);
        StagTblSPane.setViewportView(StagiaireListTbl);

        javax.swing.GroupLayout StagContentPnlLayout = new javax.swing.GroupLayout(StagContentPnl);
        StagContentPnl.setLayout(StagContentPnlLayout);
        StagContentPnlLayout.setHorizontalGroup(
            StagContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StagTblSPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        StagContentPnlLayout.setVerticalGroup(
            StagContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StagContentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StagTblSPane, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        JFrameStagPnl.add(StagContentPnl);

        JFrameTabPane.addTab("Stagiaires", JFrameStagPnl);

        JFrameFormPnl.setLayout(new javax.swing.BoxLayout(JFrameFormPnl, javax.swing.BoxLayout.Y_AXIS));

        showListformationTglBtn.setText("Afficher la liste des formations");
        showListformationTglBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showListformationTglBtnItemStateChanged(evt);
            }
        });

        addFormButton.setText("Ajouter une Formation");
        addFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormMenuPnlLayout = new javax.swing.GroupLayout(FormMenuPnl);
        FormMenuPnl.setLayout(FormMenuPnlLayout);
        FormMenuPnlLayout.setHorizontalGroup(
            FormMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormMenuPnlLayout.createSequentialGroup()
                .addComponent(showListformationTglBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FormMenuPnlLayout.setVerticalGroup(
            FormMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showListformationTglBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(addFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JFrameFormPnl.add(FormMenuPnl);

        FormationListTbl.setModel(formationTable);
        formationListScrPane.setViewportView(FormationListTbl);

        javax.swing.GroupLayout FormContentPnlLayout = new javax.swing.GroupLayout(FormContentPnl);
        FormContentPnl.setLayout(FormContentPnlLayout);
        FormContentPnlLayout.setHorizontalGroup(
            FormContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
            .addGroup(FormContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(formationListScrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE))
        );
        FormContentPnlLayout.setVerticalGroup(
            FormContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(FormContentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormContentPnlLayout.createSequentialGroup()
                    .addContainerGap(43, Short.MAX_VALUE)
                    .addComponent(formationListScrPane, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        JFrameFormPnl.add(FormContentPnl);

        JFrameTabPane.addTab("Formations", JFrameFormPnl);

        getContentPane().add(JFrameTabPane, java.awt.BorderLayout.NORTH);

        MenuFile.setText("File");
        JFrameMenu.add(MenuFile);

        MenuEdit.setText("Edit");
        JFrameMenu.add(MenuEdit);

        MenuFAQ.setText("?");
        JFrameMenu.add(MenuFAQ);

        setJMenuBar(JFrameMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFormButtonActionPerformed
        AddFormationDlg formationDlg =new AddFormationDlg(this, true);
        formationDlg.setVisible(true);
    }//GEN-LAST:event_addFormButtonActionPerformed

    private void showListformationTglBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showListformationTglBtnItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            FormContentPnl.setVisible(true);       
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            FormContentPnl.setVisible(false);           
        }
    }//GEN-LAST:event_showListformationTglBtnItemStateChanged

    private void showStagiaireListTglBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showStagiaireListTglBtnItemStateChanged
       if (evt.getStateChange() == ItemEvent.SELECTED) {
            StagContentPnl.setVisible(true);       
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            StagContentPnl.setVisible(false);           
        }
     
    }//GEN-LAST:event_showStagiaireListTglBtnItemStateChanged

    private void addStagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStagButtonActionPerformed
        AddStagiaireDlg stagiaireDlg =new AddStagiaireDlg(this, true);
        stagiaireDlg.setVisible(true);
    }//GEN-LAST:event_addStagButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    public FormationTable getFormationTable() {
        return formationTable;
    }
    
    public StagiaireTable getStagiaireTable() {
        return stagiaireTable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel FormContentPnl;
    private javax.swing.JPanel FormMenuPnl;
    public javax.swing.JTable FormationListTbl;
    public javax.swing.JPanel JFrameFormPnl;
    private javax.swing.JMenuBar JFrameMenu;
    public javax.swing.JPanel JFrameStagPnl;
    private javax.swing.JTabbedPane JFrameTabPane;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFAQ;
    private javax.swing.JMenu MenuFile;
    public javax.swing.JPanel StagContentPnl;
    private javax.swing.JPanel StagMenuPnl;
    private javax.swing.JScrollPane StagTblSPane;
    private javax.swing.JTable StagiaireListTbl;
    private javax.swing.JButton addFormButton;
    private javax.swing.JButton addStagButton;
    private javax.swing.JScrollPane formationListScrPane;
    private javax.swing.JToggleButton showListformationTglBtn;
    private javax.swing.JToggleButton showStagiaireListTglBtn;
    // End of variables declaration//GEN-END:variables
}
