<?php

namespace AppBundle\Repository;

/**
 * usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usersRepository extends \Doctrine\ORM\EntityRepository
{
    // Réccupération des informations de l'utilisateur dans la BDD
    function getUserInformations($userId) {

                $query = $this->createQueryBuilder('u');
                $query
                    ->where('u.id = :id')
                    ->setParameter('id', $userId);

                    return $query
                    ->getQuery()
                    ->getResult();                           
    }
}
