# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AppBundle\Entity\users: plaintext

  role_hierarchy:
    ROLE_MODERATEUR:  [ROLE_AUTEUR]
    ROLE_ADMIN:       [ROLE_MODERATEUR]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
      main:
          entity:
              class: AppBundle\Entity\users
              property: username
    

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
        pattern: ^/
        anonymous: true
        provider: main
        form_login:
            login_path: login
            check_path: login_check
        logout:
            path: logout
            target: /
        
  access_control:
      - { path: admin, roles: ROLE_ADMIN }
#    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        
        